/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AnimationEditorPanel.java
 *
 * Created on Oct 5, 2010, 3:44:05 AM
 */

package com.tespirit.bamporter.editor;

/**
 *
 * @author Dennis McAutoKnight
 */
public class AnimationEditorPanel extends javax.swing.JPanel {

    /**
	 * 
	 */
	private static final long serialVersionUID = 7075047447487715862L;
	/** Creates new form AnimationEditorPanel */
    public AnimationEditorPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mName = new javax.swing.JTextField();
        mNewClip = new javax.swing.JButton();
        mClips = new javax.swing.JComboBox();
        mSkeletons = new javax.swing.JComboBox();
        javax.swing.JLabel nameLabel = new javax.swing.JLabel();
        javax.swing.JLabel clipsLabel = new javax.swing.JLabel();
        javax.swing.JLabel skeletonLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        mPlay = new javax.swing.JToggleButton();
        mRestart = new javax.swing.JButton();
        mReverse = new javax.swing.JCheckBox();

        setPreferredSize(new java.awt.Dimension(225, 120));

        mNewClip.setText("New");

        mClips.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        mSkeletons.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        nameLabel.setText("Name");

        clipsLabel.setText("Clips");

        skeletonLabel.setText("Skeleton");

        mPlay.setText("Play");

        mRestart.setText("Restart");

        mReverse.setText("Reverse");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel)
                    .addComponent(clipsLabel)
                    .addComponent(skeletonLabel)
                    .addComponent(mPlay))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mReverse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(mRestart))
                    .addComponent(mSkeletons, 0, 172, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mClips, 0, 113, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mNewClip))
                    .addComponent(mName, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)))
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clipsLabel)
                    .addComponent(mClips, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mNewClip))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(skeletonLabel)
                    .addComponent(mSkeletons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mPlay)
                    .addComponent(mReverse)
                    .addComponent(mRestart)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    javax.swing.JComboBox mClips;
    javax.swing.JTextField mName;
    javax.swing.JButton mNewClip;
    javax.swing.JToggleButton mPlay;
    javax.swing.JButton mRestart;
    javax.swing.JCheckBox mReverse;
    javax.swing.JComboBox mSkeletons;
    // End of variables declaration//GEN-END:variables

}
