/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NodeEditorPanel.java
 *
 * Created on Oct 5, 2010, 4:41:57 AM
 */

package com.tespirit.bamporter.editor;

/**
 *
 * @author Dennis McAutoKnight
 */
public class NodeEditorPanel extends javax.swing.JPanel {

    /**
	 * 
	 */
	private static final long serialVersionUID = 3584090582092645768L;
	/** Creates new form NodeEditorPanel */
    public NodeEditorPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mMinX = new javax.swing.JSpinner();
        mMaxX = new javax.swing.JSpinner();
        mMaxY = new javax.swing.JSpinner();
        mMinY = new javax.swing.JSpinner();
        mMinZ = new javax.swing.JSpinner();
        mMaxZ = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jLabel1.setText("Name");

        jLabel2.setText("Bounding Box");

        jLabel3.setText("Min");

        jLabel4.setText("Max");

        mMinX.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), null, null, Float.valueOf(0.1f)));
        mMinX.setEditor(new javax.swing.JSpinner.NumberEditor(mMinX, ""));
        mMinX.setMinimumSize(new java.awt.Dimension(50, 20));
        mMinX.setPreferredSize(new java.awt.Dimension(50, 20));

        mMaxX.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), null, null, Float.valueOf(0.1f)));
        mMaxX.setEditor(new javax.swing.JSpinner.NumberEditor(mMaxX, ""));
        mMaxX.setMinimumSize(new java.awt.Dimension(50, 20));
        mMaxX.setPreferredSize(new java.awt.Dimension(50, 20));

        mMaxY.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), null, null, Float.valueOf(0.1f)));
        mMaxY.setEditor(new javax.swing.JSpinner.NumberEditor(mMaxY, ""));
        mMaxY.setMinimumSize(new java.awt.Dimension(50, 20));
        mMaxY.setPreferredSize(new java.awt.Dimension(50, 20));

        mMinY.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), null, null, Float.valueOf(0.1f)));
        mMinY.setEditor(new javax.swing.JSpinner.NumberEditor(mMinY, ""));
        mMinY.setMinimumSize(new java.awt.Dimension(50, 20));
        mMinY.setPreferredSize(new java.awt.Dimension(50, 20));

        mMinZ.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), null, null, Float.valueOf(0.1f)));
        mMinZ.setEditor(new javax.swing.JSpinner.NumberEditor(mMinZ, ""));
        mMinZ.setMinimumSize(new java.awt.Dimension(50, 20));
        mMinZ.setPreferredSize(new java.awt.Dimension(50, 20));

        mMaxZ.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), null, null, Float.valueOf(0.1f)));
        mMaxZ.setEditor(new javax.swing.JSpinner.NumberEditor(mMaxZ, ""));
        mMaxZ.setMinimumSize(new java.awt.Dimension(50, 20));
        mMaxZ.setPreferredSize(new java.awt.Dimension(50, 20));

        jLabel5.setText("X");

        jLabel6.setText("Y");

        jLabel7.setText("Z");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2))
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(mMinY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mMinZ, javax.swing.GroupLayout.PREFERRED_SIZE, 48, Short.MAX_VALUE)
                            .addComponent(mMinX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addContainerGap())
                            .addComponent(mMaxX, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(mMaxY, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(mMaxZ, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)))
                    .addComponent(mName, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(mName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(mMaxX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mMinX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(mMaxY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mMinY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(mMaxZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mMinZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    javax.swing.JSpinner mMaxX;
    javax.swing.JSpinner mMaxY;
    javax.swing.JSpinner mMaxZ;
    javax.swing.JSpinner mMinX;
    javax.swing.JSpinner mMinY;
    javax.swing.JSpinner mMinZ;
    javax.swing.JTextField mName;
    // End of variables declaration//GEN-END:variables

}
