/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BamporterFrame2.java
 *
 * Created on Oct 5, 2010, 4:10:56 AM
 */

package com.tespirit.bamporter.app;

/**
 *
 * @author Dennis McAutoKnight
 */
public class BamporterFrame2 extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 5628268757496150150L;
	/** Creates new form BamporterFrame2 */
    public BamporterFrame2() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mMainPanel = new javax.swing.JSplitPane();
        mEditor = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mProperties = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        mNavigator = new javax.swing.JTree();
        mMenuBar = new javax.swing.JMenuBar();
        mFile = new javax.swing.JMenu();
        mOpen = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        mSaveAll = new javax.swing.JMenuItem();
        mSaveScenes = new javax.swing.JMenuItem();
        mSaveAnimations = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        mExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bamporter");
        setName("bamporter"); // NOI18N

        mMainPanel.setDividerLocation(160);

        mEditor.setDividerLocation(240);

        jLabel1.setText("Properties");

        mProperties.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(180, Short.MAX_VALUE))
            .addComponent(mProperties, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mProperties, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE))
        );

        mEditor.setLeftComponent(jPanel1);

        mMainPanel.setRightComponent(mEditor);

        mNavigator.setAutoscrolls(true);
        mNavigator.setRootVisible(false);
        jScrollPane1.setViewportView(mNavigator);

        mMainPanel.setLeftComponent(jScrollPane1);

        mFile.setText("File");

        mOpen.setText("Open");
        mFile.add(mOpen);
        mFile.add(jSeparator1);

        mSaveAll.setText("Save All");
        mFile.add(mSaveAll);

        mSaveScenes.setText("Save Scenes");
        mFile.add(mSaveScenes);

        mSaveAnimations.setText("Save Animations");
        mFile.add(mSaveAnimations);
        mFile.add(jSeparator2);

        mExit.setText("Exit");
        mFile.add(mExit);

        mMenuBar.add(mFile);

        setJMenuBar(mMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BamporterFrame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    javax.swing.JSplitPane mEditor;
    javax.swing.JMenuItem mExit;
    private javax.swing.JMenu mFile;
    javax.swing.JSplitPane mMainPanel;
    private javax.swing.JMenuBar mMenuBar;
    javax.swing.JTree mNavigator;
    javax.swing.JMenuItem mOpen;
    javax.swing.JScrollPane mProperties;
    javax.swing.JMenuItem mSaveAll;
    javax.swing.JMenuItem mSaveAnimations;
    javax.swing.JMenuItem mSaveScenes;
    // End of variables declaration//GEN-END:variables

}
